// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJZE1EV1GUEBGfAgAkiDh1YT3hz7GxXto',
    appId: '1:1026485249736:web:98219e0a8516fe5ddb27fd',
    messagingSenderId: '1026485249736',
    projectId: 'chatapp-backend-f455d',
    authDomain: 'chatapp-backend-f455d.firebaseapp.com',
    storageBucket: 'chatapp-backend-f455d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmcYOrjZc0Rv-lTpj0iHfcjW1d2fmxLwA',
    appId: '1:1026485249736:android:cccbae9a0381dba8db27fd',
    messagingSenderId: '1026485249736',
    projectId: 'chatapp-backend-f455d',
    storageBucket: 'chatapp-backend-f455d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0QTF7bKrczZEJKEDIn1dMTkK88HwUVqU',
    appId: '1:1026485249736:ios:b8874bfe5021a327db27fd',
    messagingSenderId: '1026485249736',
    projectId: 'chatapp-backend-f455d',
    storageBucket: 'chatapp-backend-f455d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0QTF7bKrczZEJKEDIn1dMTkK88HwUVqU',
    appId: '1:1026485249736:ios:fec622ea9249853cdb27fd',
    messagingSenderId: '1026485249736',
    projectId: 'chatapp-backend-f455d',
    storageBucket: 'chatapp-backend-f455d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
